## Numpy

Numpy:- Numpy stands for numerical python and is the core library for numeric and scientific computing, It consists of multi-dimensional array objects

* Its an homogeneous in nature the numpy list contains single datatype  
* The array which we were using  doesnot supports multi-dimensional, It only allows 1(single dimension).  
* So to work on multi-dimension array we use 3rd party package called Numpy

In [1]:
!pip install numpy

In [2]:
import numpy 

In [3]:
?numpy

In [4]:
import warnings
warnings.filterwarnings("ignore")

In [1]:
import numpy as np
np.__version__

'1.23.5'

In [10]:
ar1 = np.array([3,4,4,9,0,5,0.5],dtype="int8")
print(ar1)
#type(ar1)

[3 4 4 9 0 5 0]


In [11]:
# Getting the dimensions
print(ar1.ndim)
#ndim is used to find the dimension of the array


1


In [14]:
b = np.array([[3,4,5,6],[-2,4,1,0],[23,67,44,1]])
print(b)
print(b.ndim)
print(b.shape)

[[ 3  4  5  6]
 [-2  4  1  0]
 [23 67 44  1]]
2
(3, 4)


In [41]:
c = np.array([[2,6,9,3],[2,4,5,1],[5,9,0,3],[-2,9,4,3]],dtype="float32")
# Getting the shape of the array
print(c)
print(c.shape)
#shape is used to find out the no. of rows & columns in the array


[[ 2.  6.  9.  3.]
 [ 2.  4.  5.  1.]
 [ 5.  9.  0.  3.]
 [-2.  9.  4.  3.]]
(4, 4)


In [43]:
d = np.array([(3,6,9),(5,9,0)])
d

array([[3, 6, 9],
       [5, 9, 0]])

In [16]:
e = np.array([[[2,4,5],[4,8,0],[1,9,3]],[[2,6,3],[1,-5,-3],[5,6,7]]])
print(e)
print(e.ndim)
print(e.shape)
#2 - no. of sets, 3 - no. of rows , 4 - no. of columns

[[[ 2  4  5]
  [ 4  8  0]
  [ 1  9  3]]

 [[ 2  6  3]
  [ 1 -5 -3]
  [ 5  6  7]]]
3
(2, 3, 3)


In [57]:
f = np.array([[[2,3,4],[4,5,6]]])
f.shape

(1, 2, 3)

### Indexing and Slicing

In [58]:
x = np.array([[2,3,4],[5,9,0],[2,8,7],[3,1,6]])
print(x)
print(x[1,2])
print()
print(x[3,0])
print()
print(x[2,2])
print()
print(x[0:2,0])
print()
print(x[:,2])
print()
print(x[2,:])
print()
print(x[0, ::2])

[[2 3 4]
 [5 9 0]
 [2 8 7]
 [3 1 6]]
0

3

7

[2 5]

[4 0 7 6]

[2 8 7]

[2 4]


In [59]:
a=np.array([[1,2,3,4],[3,4,5,6],[8,9,10,11]])
print(a)
print(a[2,0])
print(a[:,2])
print(a[0:2,:])

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 8  9 10 11]]
8
[ 3  5 10]
[[1 2 3 4]
 [3 4 5 6]]


In [60]:
b = np.array([[[1,3],[3,4]],[[5,6],[7,8]]],dtype='int64')
print(b)
print(b.ndim)

[[[1 3]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [61]:
print(b[0,1,1])

4


In [62]:
print(b[:,1,:])

[[3 4]
 [7 8]]


#### Initializing Different Types of Arrays

In [68]:
a1 = np.ones((2,5))
print(a1)
print()
a2 = np.ones((3,4,7),dtype="i")
print(a2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[[1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1]]]


In [70]:
b1 = np.zeros((3,5))
print(b1)
print()

b2 = np.zeros((2,2,5),dtype="int16")
print(b2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[[0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]]]


In [75]:
c1 = np.full((2,5),"x")
print(c1)

c2 = np.full((2,5,2),0.001)
print(c2)

[['x' 'x' 'x' 'x' 'x']
 ['x' 'x' 'x' 'x' 'x']]
[[[0.001 0.001]
  [0.001 0.001]
  [0.001 0.001]
  [0.001 0.001]
  [0.001 0.001]]

 [[0.001 0.001]
  [0.001 0.001]
  [0.001 0.001]
  [0.001 0.001]
  [0.001 0.001]]]


In [81]:
d = np.identity(3)
print(d)

d2 = np.identity(6,dtype="i")
print(d2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [156]:
np.random.seed(1)

new = np.random.random((2,3))
new

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]])

In [94]:
#np.random.seed(10)
#it is used to get fixed output everytime

a=np.linspace(0,50,5)
#linspace is used if I want to divide my range into
#n no.of parts
print(a)
print()

a=np.arange(0,21,3)
# it works by creating step difference in your given range by creating array
print(a)
print()

a=np.random.random((2,3))
#randomnly creates an array of desired range most
#of the times it is between 0-1
print(a)
print()

a=np.random.randint(50,101,(2,3,4))
# randomly creates an array of desired range & the arrays
#consists of integer datatype in the given range.
print(a)

[ 0.  12.5 25.  37.5 50. ]

[ 0  3  6  9 12 15 18]

[[0.85187607 0.03507378 0.87880459]
 [0.3438901  0.19889997 0.05581883]]

[[99 89 55 89]
 [69 96 56 90]
 [86 67 83 86]]


In [157]:
#np.random.seed(10)
#uniform helps to give the float output from the given range
a=np.random.uniform(50,100,(2,2,3))
print(a)

[[[59.31301057 67.27803635 69.83837371]
  [76.9408367  70.95972572 84.26097502]]

 [[60.22261249 93.90587182 51.36937966]
  [83.52337551 70.86524012 77.93449142]]]


1. Sahil
2. Umesh
3. Dhruv Soni
4. Shubham
5. Tarun Joshi
6. Anand Nambothri
7. Manoj
8. Rohan Walke

In [21]:
l1 = [[3,4],[3,6],[9,0],"str"]
print(l1)
max(l1)

[[3, 4], [3, 6], [9, 0], 'str']


TypeError: '>' not supported between instances of 'str' and 'list'

In [25]:
#aggregate functions
a=np.array([[8,9],[10,11],[12,13]])
print(a)
print(a.shape)
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(np.mean(a))

[[ 8  9]
 [10 11]
 [12 13]]
(3, 2)
8
13
63
10.5
10.5


In [28]:
import warnings
warnings.filterwarnings("ignore")

In [29]:
#math functions
a=np.array([[1,0,3],[3,4,5]])
print(np.sqrt(a))
print(np.std(a))
print(np.log(a))
b=np.sqrt(a)
print(b.round(2))
print(b.round(4))

[[1.         0.         1.73205081]
 [1.73205081 2.         2.23606798]]
1.699673171197595
[[0.               -inf 1.09861229]
 [1.09861229 1.38629436 1.60943791]]
[[1.   0.   1.73]
 [1.73 2.   2.24]]
[[1.     0.     1.7321]
 [1.7321 2.     2.2361]]


In [33]:
x = [4,0,6,7]
new = []
for i in x:
    n =i+2
    new.append(n)
    print(new)

[6]
[6, 2]
[6, 2, 8]
[6, 2, 8, 9]


In [35]:
x = [6,8,9,0]
x**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [42]:
#SIMD - Single instruction multiple data
a = np.array([4,5,6,7])
a+2

b = np.array([[2,3,4],[3,4,5]])
b%2

array([[0, 1, 0],
       [1, 0, 1]], dtype=int32)

In [43]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[3,4]])
print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x@y)

[[1 2]
 [3 4]]
[[5 6]
 [3 4]]
[[6 8]
 [6 8]]
[[-4 -4]
 [ 0  0]]
[[ 5 12]
 [ 9 16]]
[[0.2        0.33333333]
 [1.         1.        ]]
[[1 2]
 [0 0]]
[[11 14]
 [27 34]]


In [50]:
x=np.array([(1,2,3),(3,4,5)])
x[0,1]=10
print(x)
print()
x[:,0]=[-2,-10]
print(x)

[[ 1 10  3]
 [ 3  4  5]]

[[ -2  10   3]
 [-10   4   5]]


In [51]:
b = np.array([[[1,2,8],[3,4,0]],[[5,6,-3],[7,8,11]]])
print(b)
print(b.ndim)
print(b.shape)

[[[ 1  2  8]
  [ 3  4  0]]

 [[ 5  6 -3]
  [ 7  8 11]]]
3
(2, 2, 3)


In [55]:
b[0,1,:2]=[0,-3]
b

array([[[ 1,  2,  8],
        [ 0, -3,  0]],

       [[ 5,  6, -3],
        [ 7,  8, 11]]])

In [60]:
b[:,0,:]=[[3,11,33],[-8,-3,8]]
b

array([[[ 3, 11, 33],
        [ 0, -3,  0]],

       [[-8, -3,  8],
        [ 7,  8, 11]]])

In [70]:
#ravel puts the 2d 3d in 1d
b = b.ravel()
b.shape
b

array([ 3, 11, 33,  0, -3,  0, -8, -3,  8,  7,  8, 11])

In [83]:
"""
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change 
number of elements in each dimension.
"""
print(b.reshape(2,6))

[[ 3 11 33  0 -3  0]
 [-8 -3  8  7  8 11]]


In [92]:
y = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15,16,17,-3])
new = y.reshape(2,3,3)

In [93]:
new

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, -3]]])